### ISSUE TITLE
Breaks node-red

### ISSUE THREAD

**Issue by realjax** [dkijkuit/node-red-contrib-buienradar#3]
Breaks the operation of Node-Red with this error:

TypeError: Cannot read property 'nodeType' of undefined
    at PathExpr.evaluate (/Users/username/.node-red/node_modules/xpath/xpath.js:1716:17)
    at XPath.evaluate (/Users/username/.node-red/node_modules/xpath/xpath.js:1220:25)
    at XPathExpression.evaluate (/Users/username/.node-red/node_modules/xpath/xpath.js:4250:26)
    at Object.exports.selectWithResolver (/Users/jusername/.node-red/node_modules/xpath/xpath.js:4667:26)
    at Object.exports.select (/Users/username/.node-red/node_modules/xpath/xpath.js:4647:17)
    at IncomingMessage.<anonymous> (/Users/username/.node-red/node_modules/node-red-contrib-buienradar/buienradar.js:63:39)

**Comment by dkijkuit** [comment]
Can you elaborate? I cannot reproduce this behavior.

**Comment by realjax** [comment]
There's not much to elaborate I'm afraid. Tried it on two different systems and both have the problem.   Install the module in node-red ( latest stable version), drag the node in a flow, choose a station, deploy and node-red crashes.

It does show this though (sorry I didnt notice this earlier), right before the error I mentioned earlier 

**[xmldom error]	invalid document source
@#[line:0,col:undefined]**
13 Apr 12:49:24 - [red] Uncaught Exception:
13 Apr 12:49:24 - TypeError: Cannot read property 'nodeType' of undefined
..........

**Comment by dkijkuit** [comment]
Version 0.2.2 published to npm, please upgrade to the latest version and let me know if it works.

**Comment by realjax** [comment]
Fixed, thanks!
