### ISSUE TITLE
node-red crashes on DNS errors

### ISSUE THREAD

**Issue by srijken** [dkijkuit/node-red-contrib-buienradar#4]
I think there's some error-handling missing?

```
15 May 07:59:06 - Error: getaddrinfo ENOTFOUND xml.buienradar.nl xml.buienradar.nl:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
```

**Comment by dkijkuit** [comment]
Fixed: b130b91d2b7f7b8edda447ac18722cac99cea5ac
