### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by rikki78** [dkijkuit/node-red-contrib-buienradar#7]
Hello there...
Today I got this exception, making my node red crash...

````
22 Sep 19:49:33 - [info] [buienradar:fb602b78.768208] Node: 15
[xmldom error]  invalid document source
@#[line:0,col:undefined]
22 Sep 19:49:33 - [red] Uncaught Exception:
22 Sep 19:49:33 - TypeError: Cannot read property 'nodeType' of undefined
at PathExpr.evaluate (/home/pi/.node-red/node_modules/xpath/xpath.js:1716:17)
at XPath.evaluate (/home/pi/.node-red/node_modules/xpath/xpath.js:1220:25)
at XPathExpression.evaluate (/home/pi/.node-red/node_modules/xpath/xpath.js:4250:26)
at Object.exports.selectWithResolver (/home/pi/.node-red/node_modules/xpath/xpath.js:4667:26)
at Object.exports.select (/home/pi/.node-red/node_modules/xpath/xpath.js:4647:17)
at IncomingMessage.<anonymous> (/home/pi/.node-red/node_modules/node-red-contrib-buienradar/buienradar.js:72:39)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
nodered.service: main process exited, code=exited, status=1/FAILURE
````
Any idea what can be wrong?

**Comment by dkijkuit** [comment]
No idea, does the error still occur?

**Comment by rikki78** [comment]
It happened a couple of times and I have removed the nodes from the flow
now, so I am not sure if it still occurs.
Do you need more information?

Op za 22 sep. 2018 20:52 schreef David <notifications@github.com>:

**Comment by dkijkuit** [comment]
What is the update interval for polling the server?

**Comment by rikki78** [comment]
I believe 10 minutes but I will double check it.



Op ma 24 sep. 2018 09:53 schreef David <notifications@github.com>:

**Comment by rikki78** [comment]
It seems the interval was at 1 minute (from the logs I see this every minute)
```
22 Sep 19:38:49 - [info] [buienradar:62b3cd28.721e94] Node: 15
```

**Comment by dkijkuit** [comment]
I recommend to increase the interval to at least 10 minutes and check whether the issue persists.
